add: ipfs on the proposal query
Liqwid-Labs/liqwid-api pull request #15
Opened 2023-08-14 22:00 UTC by rcheiko

2023-08-15 20:16 UTC, Banou26 requested changes

2023-08-15 20:16 UTC, Banou26 commented on src/worker/agora/proposals.ts
> +      ipfs: ipfsLink
If `proposalMetadata.description.startsWith` is false, `ipfsLink` will return `https://ipfs.io/ipfs/` which is not good, you can change this by returning undefined in a ternary.

2023-08-18 12:50 UTC, Banou26 commented on src/worker/agora/proposals.ts
> +      ipfs: ipfsLink
Could you squash the commits please? Should be good after that

2023-08-18 16:10 UTC, rcheiko commented on src/worker/agora/proposals.ts
> +      ipfs: ipfsLink
Yes, it's done

2023-08-21 10:40 UTC, Banou26 approved these changes

2023-08-21 10:40 UTC, merged